// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bagplot_compute
List bagplot_compute(NumericMatrix xy, double factor, double eps, bool dither);
RcppExport SEXP _aurora_bagplot_compute(SEXP xySEXP, SEXP factorSEXP, SEXP epsSEXP, SEXP ditherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type factor(factorSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type dither(ditherSEXP);
    rcpp_result_gen = Rcpp::wrap(bagplot_compute(xy, factor, eps, dither));
    return rcpp_result_gen;
END_RCPP
}
// formatDateTime
CharacterVector formatDateTime(SEXP x, std::string fmt, bool strict, std::string locale);
RcppExport SEXP _aurora_formatDateTime(SEXP xSEXP, SEXP fmtSEXP, SEXP strictSEXP, SEXP localeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< std::string >::type locale(localeSEXP);
    rcpp_result_gen = Rcpp::wrap(formatDateTime(x, fmt, strict, locale));
    return rcpp_result_gen;
END_RCPP
}
// formatNum
CharacterVector formatNum(NumericVector x, Nullable<IntegerVector> digits, Nullable<IntegerVector> leadDigits, Nullable<CharacterVector> bigMark, Nullable<CharacterVector> decimalMark, int sciBig, int sciSmall);
RcppExport SEXP _aurora_formatNum(SEXP xSEXP, SEXP digitsSEXP, SEXP leadDigitsSEXP, SEXP bigMarkSEXP, SEXP decimalMarkSEXP, SEXP sciBigSEXP, SEXP sciSmallSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type digits(digitsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type leadDigits(leadDigitsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type bigMark(bigMarkSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type decimalMark(decimalMarkSEXP);
    Rcpp::traits::input_parameter< int >::type sciBig(sciBigSEXP);
    Rcpp::traits::input_parameter< int >::type sciSmall(sciSmallSEXP);
    rcpp_result_gen = Rcpp::wrap(formatNum(x, digits, leadDigits, bigMark, decimalMark, sciBig, sciSmall));
    return rcpp_result_gen;
END_RCPP
}
// pSmirnov2x
double pSmirnov2x(double statistic, int nx, int ny);
RcppExport SEXP _aurora_pSmirnov2x(SEXP statisticSEXP, SEXP nxSEXP, SEXP nySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    rcpp_result_gen = Rcpp::wrap(pSmirnov2x(statistic, nx, ny));
    return rcpp_result_gen;
END_RCPP
}
// pKS2
NumericVector pKS2(NumericVector statistic, double tol);
RcppExport SEXP _aurora_pKS2(SEXP statisticSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(pKS2(statistic, tol));
    return rcpp_result_gen;
END_RCPP
}
// pKolmogorov2x
double pKolmogorov2x(double statistic, int n);
RcppExport SEXP _aurora_pKolmogorov2x(SEXP statisticSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(pKolmogorov2x(statistic, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aurora_bagplot_compute", (DL_FUNC) &_aurora_bagplot_compute, 4},
    {"_aurora_formatDateTime", (DL_FUNC) &_aurora_formatDateTime, 4},
    {"_aurora_formatNum", (DL_FUNC) &_aurora_formatNum, 7},
    {"_aurora_pSmirnov2x", (DL_FUNC) &_aurora_pSmirnov2x, 3},
    {"_aurora_pKS2", (DL_FUNC) &_aurora_pKS2, 2},
    {"_aurora_pKolmogorov2x", (DL_FUNC) &_aurora_pKolmogorov2x, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_aurora(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
