# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bagplot_compute <- function(xy, factor = 3.0, eps = 1e-8, dither = TRUE) {
    .Call(`_aurora_bagplot_compute`, xy, factor, eps, dither)
}

formatDateTime <- function(x, fmt, strict = TRUE, locale = "current") {
    .Call(`_aurora_formatDateTime`, x, fmt, strict, locale)
}

formatNum <- function(x, digits = NULL, ldigits = NULL, big_mark = NULL, decimal_mark = NULL, sci_big = 9999L, sci_small = -9999L) {
    .Call(`_aurora_formatNum`, x, digits, ldigits, big_mark, decimal_mark, sci_big, sci_small)
}

pSmirnov2x <- function(statistic, nx, ny) {
    .Call(`_aurora_pSmirnov2x`, statistic, nx, ny)
}

pKS2 <- function(statistic, tol) {
    .Call(`_aurora_pKS2`, statistic, tol)
}

pKolmogorov2x <- function(statistic, n) {
    .Call(`_aurora_pKolmogorov2x`, statistic, n)
}

