# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bagplot_compute_cpp <- function(xy, factor = 3.0, eps = 1e-8, dither = FALSE) {
    .Call(`_pharos_bagplot_compute_cpp`, xy, factor, eps, dither)
}

formatDateTimeUtc_cpp <- function(x, fmt, strict = TRUE, locale = "current") {
    .Call(`_pharos_formatDateTimeUtc_cpp`, x, fmt, strict, locale)
}

formatNum_cpp <- function(x, digits = NULL, leadDigits = NULL, bigMark = NULL, decimalMark = NULL, sciBig = 9999L, sciSmall = -9999L) {
    .Call(`_pharos_formatNum_cpp`, x, digits, leadDigits, bigMark, decimalMark, sciBig, sciSmall)
}

pKolmogorov2x_cpp <- function(statistic, n) {
    .Call(`_pharos_pKolmogorov2x_cpp`, statistic, n)
}

pSmirnov2x_cpp <- function(statistic, nx, ny) {
    .Call(`_pharos_pSmirnov2x_cpp`, statistic, nx, ny)
}

pKS2_cpp <- function(statistic, tol) {
    .Call(`_pharos_pKS2_cpp`, statistic, tol)
}

